"use client"
import Navbar from '@/components/Heading/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './Providers'
import Footersection from '@/components/Footer/Footersection'
import GlobalState from '@/context/ProductContextProvider'
import CartState from '@/context/CartContext'
import { ProvidersSession } from './ProvidersSession'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersSession>
        <GlobalState>
          <CartState>       
            <Providers>
              <div className='flex flex-col' >
                <div className=''>
                  <Navbar />
                </div>
                {children}
                <div >
                  <Footersection/>
                </div>
              </div>
            </Providers>
            </CartState>
        </GlobalState>
        </ProvidersSession>
      </body>
    </html>
  )
}
